const API = {
  login: '/user/user/login',
  register: '/user/user/register',
  initChat: '/chat/chat/init',
  saveChat: '/chat/chat/save',
  saveUserWords: '/chat/chat/saveUserWords',
  interviewStart: '/api/chat/interview/start',
  getChatData: '/chat/chat/getChatData',
  interviewAnswer: '/api/chat/interview/answer',
  interviewHelp: '/api/chat/interview/help',
  initSession: '/chat/session/initSession',
  getSessionList: '/chat/session/getSessionList',
  getUserInfo: '/user/user/getUserInfo',
  updateArea: '/user/area/updateArea',
  setArea: '/user/area/setArea',
  getMindmapData: '/mindmap/mindmap/getMindmapData',
  saveMindmapData: '/mindmap/mindmap/saveMindmapData',
  getSubcategory: '/mindmap/mindmap/getSubcategory',
  initNote: '/note/note/initNote',
  getNote: '/api/note/note/getNote',
  saveNote: '/note/note/saveNote',
  getNoteData: '/note/note/getNoteData',
  updateNote: '/note/note/updateNote',
  deleteChat: '/chat/chat/deleteChat',
  deleteSession: '/chat/session/deleteSession',
  initPrefer: '/perfer/perfer/initPrefer',
  getPreferList: '/perfer/perfer/getPreferList',
  getdetailChats: '/perfer/perfer/getdetailChats',
  deletePrefer: '/perfer/perfer/deletePrefer',
}

export default API
