const API = {
  initChat: '/api/chat/chat/init',
  saveChat: '/api/chat/chat/save',
  saveUserWords: '/api/chat/chat/saveUserWords',
  interviewStart: '/api/chat/interview/start',
  getChatData: '/api/chat/chat/getChatData',
  interviewAnswer: '/api/chat/interview/answer',
  interviewHelp: '/api/chat/interview/help',
  initSession: '/api/chat/session/initSession',
  getSessionList: '/api/chat/session/getSessionList',
  getUserInfo: '/api/user/user/getUserInfo',
  updateArea: '/api/user/area/updateArea',
  setArea: '/api/user/area/setArea',
  getMindmapData: '/api/mindmap/mindmap/getMindmapData',
  saveMindmapData: '/api/mindmap/mindmap/saveMindmapData',
  getSubcategory: '/api/mindmap/mindmap/getSubcategory',
  initNote: '/api/note/note/initNote',
  getNote: '/api/note/note/getNote',
  saveNote: '/api/note/note/saveNote',
  getNoteData: '/api/note/note/getNoteData',
  updateNote: '/api/note/note/updateNote',
  deleteChat: '/api/chat/chat/deleteChat',
  deleteSession: '/api/chat/session/deleteSession',
  initPrefer: '/api/perfer/perfer/initPrefer',
  getPreferList: '/api/perfer/perfer/getPreferList',
  getdetailChats: '/api/perfer/perfer/getdetailChats',
  deletePrefer: '/api/perfer/perfer/deletePrefer',
}

export default API
